baseURL = 'https://itibbers.com/'
languageCode = 'en-us'
title = 'itibbers'
theme = 'PaperMod'

# PaperModä¸»é¢˜é…ç½®
[params]
  # ç½‘ç«™æè¿°
  description = "itibbers - åˆ†äº«æŠ€æœ¯ã€ç”Ÿæ´»å’Œæ€è€ƒçš„ä¸ªäººåšå®¢"
  keywords = ["æŠ€æœ¯åšå®¢", "ç¼–ç¨‹", "å¼€å‘", "å‰ç«¯", "ç”Ÿæ´»", "æ€è€ƒ", "itibbers"]
  author = "itibbers"
  images = ["/og-image.png"]

  # æ˜¾ç¤ºé€‰é¡¹
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # SEOå¢å¼º
  env = "production"
  defaultTheme = "auto"
  disableThemeToggle = false
  DateFormat = "January 2, 2006"
  displayFullLangName = true
  ShowFullTextinRSS = true

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

  [params.label]
    text = "itibbers"
    icon = "/apple-touch-icon.png"
    iconHeight = 35

  # profile-mode
  [params.profileMode]
    enabled = false
    title = "ExampleSite"
    subtitle = "This is subtitle"
    imageUrl = "<title or url of image>"
    imageWidth = 120
    imageHeight = 120
    imageTitle = "my image"

  # home-info mode
  [params.homeInfoParams]
    Title = "Hi there ğŸ‘‹"
    Content = "æ¬¢è¿æ¥åˆ° itibbers çš„ä¸ªäººåšå®¢ï¼Œåˆ†äº«æŠ€æœ¯ã€ç”Ÿæ´»å’Œæ€è€ƒ"

  # Open Graph / Twitter Card
  [params.OpenGraph]
    type = "website"
    locale = "zh_CN"
    url = "https://itibbers.com/"
    site_name = "itibbers"

  [params.TwitterCard]
    card = "summary_large_image"
    site = "@itibbers"
    creator = "@itibbers"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/"

  # [[params.socialIcons]]
  #   name = "stackoverflow"
  #   url = "https://stackoverflow.com"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

    [[languages.en.menu.main]]
      name = "Archive"
      url = "/archives/"
      weight = 10

    [[languages.en.menu.main]]
      name = "Search"
      url = "/search/"
      weight = 20

    [[languages.en.menu.main]]
      name = "Tags"
      url = "/tags/"
      weight = 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true
[markup.highlight]
  noClasses = false
